service: language-bot
frameworkVersion: "2"
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: handler/slack-event.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
